### ISSUE TITLE
Support for RAML 0.8

### ISSUE THREAD

**Issue by harikrishnanmurthy** [reallyinsane/raml-to-jaxrs-jsr-250-plugin#1]
Hello,
Am currently trying to inject JSR-250 annotations using your plugin but am having issues while generating the java code from the RAML. Maven complains the moment i put in the plugins attribute.

Does this plugin work with RAML 0.8 or only 1.0 upwards?

**Comment by reallyinsane** [comment]
I think that the plugin mechanism provided by raml-to-jaxrs is not available for RAML 0.8. That's why my plugin will not be used then. Perhaps you could try it with RAML 1.0.
